import Head from "next/head";

import { api } from "@/utils/api";

import Header from "@/components/headers/Main";
import Sojourns from "@/components/headers/Sojourns";
import FiltersForm from "@/components/headers/FiltersForm";
import Advertisement from "@/components/cards/advertisement";
import { Box, Flex, Skeleton } from "@chakra-ui/react";

export default function Home() {
  // const hello = api.post.hello.useQuery({ text: "from tRPC" });

  const { data: propertiesData } = api.property.list.useQuery({});
  // console.log(propertiesData);

  // const advs = [
  //   {
  //     id: 1,
  //     title: "Hotel Bianchi",
  //     description: "Vicino al mare",
  //     slides: [
  //       "/media/test/adv1.webp",
  //       "/media/test/adv2.webp",
  //       "/media/test/adv3.webp",
  //       "/media/test/adv4.webp",
  //     ],
  //     price: {
  //       value: 150,
  //       sale: 100,
  //       currency: "EUR",
  //     },
  //   },
  //   {
  //     id: 2,
  //     title: "Hotel Rossi",
  //     description: "Vicino al mare",
  //     slides: [
  //       "/media/test/adv2.webp",
  //       "/media/test/adv1.webp",
  //       "/media/test/adv3.webp",
  //       "/media/test/adv4.webp",
  //     ],
  //     price: {
  //       value: 150,
  //       sale: 100,
  //       currency: "EUR",
  //     },
  //   },
  //   {
  //     id: 3,
  //     title: "Hotel Verdi",
  //     description: "Vicino al mare",
  //     slides: [
  //       "/media/test/adv3.webp",
  //       "/media/test/adv1.webp",
  //       "/media/test/adv2.webp",
  //       "/media/test/adv4.webp",
  //     ],
  //     price: {
  //       value: 150,
  //       sale: 100,
  //       currency: "EUR",
  //     },
  //   },
  //   {
  //     id: 4,
  //     title: "Hotel Gialli",
  //     description: "Vicino al mare",
  //     slides: [
  //       "/media/test/adv4.webp",
  //       "/media/test/adv1.webp",
  //       "/media/test/adv2.webp",
  //       "/media/test/adv3.webp",
  //     ],
  //     price: {
  //       value: 150,
  //       sale: 100,
  //       currency: "EUR",
  //     },
  //   },
  //   {
  //     id: 5,
  //     title: "Hotel Blu",
  //     description: "Vicino al mare",
  //     slides: [
  //       "/media/test/adv1.webp",
  //       "/media/test/adv2.webp",
  //       "/media/test/adv3.webp",
  //       "/media/test/adv4.webp",
  //     ],
  //     price: {
  //       value: 150,
  //       sale: 100,
  //       currency: "EUR",
  //     },
  //   },
  //   {
  //     id: 6,
  //     title: "Hotel Marroni",
  //     description: "Vicino al mare",
  //     slides: [
  //       "/media/test/adv2.webp",
  //       "/media/test/adv1.webp",
  //       "/media/test/adv3.webp",
  //       "/media/test/adv4.webp",
  //     ],
  //     price: {
  //       value: 150,
  //       sale: 100,
  //       currency: "EUR",
  //     },
  //   },
  // ];

  const advertisementImages = [
    ["/media/test/hotel-prova.jpg"],
    ["/media/test/hotel1.jpg"],
    ["/media/test/hotel2.jpg"],
    ["/media/test/hotel3.jpg"],
  ];

  return (
    <>
      <Head>
        <title>Praia dei Borghi</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header />
        <Box mt={2} mb={6}>
          <FiltersForm />
        </Box>
        <Sojourns />
        <Flex
          justifyContent={"center"}
          flexWrap={"wrap"}
          gap={10}
          p={{
            base: 5,
            md: 10,
          }}
        >
          {/* {advs.map((adv) => {
            return (
              <Advertisement
                key={adv.id}
                id={adv.id}
                title={adv.title}
                description={adv.description}
                slides={adv.slides}
                price={adv.price}
              />
            );
          })} */}
          {propertiesData ? (
            propertiesData.map((adv, index) => {
              return (
                <Advertisement
                  key={adv.id}
                  id={adv.id}
                  title={adv.name}
                  description={adv.city ?? ""}
                  slides={
                    adv.images.length > 0
                      ? adv.images
                      : advertisementImages[index] ?? []
                  }
                  price={{
                    value: 22,
                    sale: 20,
                    currency: "€",
                  }}
                />
              );
            })
          ) : (
            <Skeleton height="250px" width="250px" />
          )}
        </Flex>
        {/* <div className={styles.showcaseContainer}>
            <p className={styles.showcaseText}>
              {hello.data ? hello.data.greeting : "Loading tRPC query..."}
            </p>
            <AuthShowcase />
          </div> */}
      </main>
    </>
  );
}

// function AuthShowcase() {
//   const { data: sessionData } = useSession();

//   const { data: secretMessage } = api.post.getSecretMessage.useQuery(
//     undefined, // no input
//     { enabled: sessionData?.user !== undefined }
//   );

//   return (
//     <div className={styles.authContainer}>
//       <p className={styles.showcaseText}>
//         {sessionData && <span>Logged in as {sessionData.user?.name}</span>}
//         {secretMessage && <span> - {secretMessage}</span>}
//       </p>
//       <button
//         className={styles.loginButton}
//         onClick={sessionData ? () => void signOut() : () => void signIn()}
//       >
//         {sessionData ? "Sign out" : "Sign in"}
//       </button>
//     </div>
//   );
// }
